
POST http://localhost:9900/projects/3/milestone
Content-Type: application/json

{
  "mileStoneName": "테스트 마일스톤",
  "dateStart": "2024-02-25",
  "dateFinish": "2024-02-28"
}

###
GET http://localhost:9900/projects/3/milestone
Accept: application/json

###

GET http://localhost:9900/projects/3/milestone/1
Accept: application/json

###

DELETE http://localhost:9900/projects/3/milestone/1