###
###
GET http://localhost:9900/projectmembers/3
Accept: application/json


###
POST http://localhost:9900/projectmembers
Content-Type: application/json

{
  "projectNumber" : 18,
  "userName": "유승진"
}


###
DELETE http://localhost:9900/projectmembers/15
Accept: application/json